version: '3.4'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
